/* 
 This file was generated by Dashcode.  
 You may edit this file to customize your widget or web page 
 according to the license.txt file included in the project.
 */

//
// Function: load()
// Called by HTML body element's onload event when the web application is ready to start
//
function load()
{
  dashcode.setupParts();
  return;
}

// -- get services helpers 

var gobjTheServices = new Services();
var gstrBaseUrl = 'http://localhost:9000';
function Services() {  
  var _objTheGreeterService = null;  
  this.getGreeterService = function()  {
    if(_objTheGreeterService == null) {
      _objTheGreeterService = new apache_org_hello_world_soap_http_Greeter();
      _objTheGreeterService.url = gstrBaseUrl + '/SimpleService';
    }
    return _objTheGreeterService;
  }

  var _objTheBeverageService = null;
  this.getBeverageService = function() {
    if(_objTheBeverageService == null) {
      _objTheBeverageService = new urn_cxf_apache_org_beverage_BeverageService();
      _objTheBeverageService.url = gstrBaseUrl + '/BeverageService';
    }
    return _objTheBeverageService;
  }

  var _objTheBankService = null;
  this.getBankService = function() {
    if(_objTheBankService == null) {
      _objTheBankService = new urn_cxf_apache_org_bank_BankService();
      _objTheBankService.url = gstrBaseUrl + '/BankService';
    }
    return _objTheBankService;
  }
}

// ------------------------

function onClickMain(objEvent) {
  // made sure the name of the item matches the name of
  // the next view. this is how/why this works ...
  var strNextView = event.target.innerText;
  var objBrowser = document.getElementById('browser').object;
  objBrowser.goForward(document.getElementById(strNextView), strNextView);
  return;
}

// ------------------------

function onClickMainSimple(objEvent) {
  // same trick again ...
  var strNextView = 'Simple' + event.target.innerText;
  var objBrowser = document.getElementById('browser').object;
  objBrowser.goForward(document.getElementById(strNextView), strNextView);
  return;
}

// ------------------------

function onClickMainSimpleSayHi(objEvent) {
  var objGreeterService = gobjTheServices.getGreeterService();
  objGreeterService.sayHi(cbSuccessMainSimpleSayHi, cbFailureMainSimpleSayHi);
  return;
}

function cbSuccessMainSimpleSayHi(response) {
  var result = document.getElementById('mainSimpleSayHi_Result');
  result.value = response.getResponseType();
  return;
}

function cbFailureMainSimpleSayHi(error) {
  alert(error);
  return;
}

// ------------------------

function onClickMainSimpleGreetMe(objEvent) {
  var strName = document.getElementById('mainSimpleGreetMe_Name').value;
  var objGreeterService = gobjTheServices.getGreeterService();
  objGreeterService.greetMe(cbSuccessMainSimpleGreetMe, cbFailureMainSimpleGreetMe, strName);
  return;
}

function cbSuccessMainSimpleGreetMe(response) {
  var result = document.getElementById('mainSimpleGreetMe_Result');
  result.value = response.getResponseType();
  return;
}

function cbFailureMainSimpleGreetMe(error) {
  alert(error);
  return;
}

// ------------------------

function onClickMainBeverage(objEvent) {
  var objCategory = document.getElementById('mainBeverage_Category'); 
  var strCategory = objCategory.options[objCategory.selectedIndex].value;
  var objBeverageService = gobjTheServices.getBeverageService();
  objBeverageService.getBeverageWithIngredientCategory(cbSuccessMainBeverage, cbFailureMainBeverage, strCategory);
  return;
}

function cbSuccessMainBeverage(response) {
  var objBeverages = response.getItem();
  var strResult = "";
  for(b in objBeverages) {
    strResult = strResult + objBeverages[b].getName();
    strResult = strResult + "\n";
  }
  var objResult = document.getElementById('mainBeverage_Result');
  objResult.value = strResult;
  return;
}

function cbFailureMainBeverage(error) {
  alert(error);
  return;
}

// ------------------------

var gstrUsername = '';
function onClickMainBankLogin(objEvent) {
  gstrUsername = document.getElementById('mainBankLogin_Username').value;
  var objBankService = gobjTheServices.getBankService();
  objBankService.login(cbSuccessMainBankLogin, cbFailureMainBankLogin, gstrUsername);
  return;
}

function cbSuccessMainBankLogin(response) {
  var blnUserWasSuccessfullyAuthenticated = response;
  if(!blnUserWasSuccessfullyAuthenticated) {
    gstrUsername = '';
    return;
  }

  var strNextView = 'BankHome';
  var objBrowser = document.getElementById('browser').object;
  objBrowser.goForward(document.getElementById(strNextView), strNextView);
  return;
}

function cbFailureMainBankLogin(error) {
  alert(error);  
  return;
}

// ------------------------

function onClickMainBankSetupPayee(objEvent) {
  var strNextView = 'BankSetupPayee';
  var objBrowser = document.getElementById('browser').object;
  objBrowser.goForward(document.getElementById(strNextView), strNextView);
  return;
}

function onClickMainBankPayPayee(event) {
  var objBankService = gobjTheServices.getBankService();
  objBankService.getCustomers(cbSuccessMainBankPayPayeeInit, cbFailureMainBankPayPayeeInit);
  return;
}

function cbSuccessMainBankPayPayeeInit(response) {
  // get rid of the old customer list (<select id="to"><option>...)
  var objCurSelectNode = document.getElementById('mainBankPayPayee_To');
  var objCurOptionNodes = objCurSelectNode.getElementsByTagName('option');
  var intCurOptionNodesLength = objCurOptionNodes.length;
  for(var i=0; i<intCurOptionNodesLength; i++) {
    objCurSelectNode.removeChild(objCurOptionNodes[0]);
  }    

  // now create a new set of <option> elements and append them
  // to the <select> node
  var objCustomers = response.getItem();
  for(c in objCustomers) {
    var strCustomerName = objCustomers[c].getName();
    var objNewOptionNode = document.createElement('option');
    objNewOptionNode.appendChild(document.createTextNode(strCustomerName));
    objCurSelectNode.appendChild(objNewOptionNode);
  }

  // display the new/updated payment screen
  var strNextView = 'BankPayPayee';
  var objBrowser = document.getElementById('browser').object;
  objBrowser.goForward(document.getElementById(strNextView), strNextView);
  return;
} 

function cbFailureMainBankPayPayeeInit(error) {
  alert(error);
  return;
}

function onClickMainBankHistory(event) {
  var objBankService = gobjTheServices.getBankService();
  objBankService.getTransactions(cbSuccessMainBankHistoryInit, cbFailureMainBankHistoryInit, gstrUsername);
  return;
}

function cbSuccessMainBankHistoryInit(response) {
  // get rid of the old transaction list (<ul id="transactions"><li><center>...)
  var objCurListNode = document.getElementById('mainBankHistory_Transactions');
  var objCurListItemNodes = objCurListNode.getElementsByTagName('li');
  var intCurListItemNodesLength = objCurListItemNodes.length;
  for(var i=0; i<intCurListItemNodesLength; i++) {
    objCurListNode.removeChild(objCurListItemNodes[0]);
  }    

  // build up a/the new transaction list
  var objTransactions = response.getItem();
  for(t in objTransactions) {
    var strTo = objTransactions[t].getTo();
    var strAmount = objTransactions[t].getAmount();

    var objNewListItemNode = document.createElement('li');
    objNewListItemNode.appendChild(document.createTextNode(strTo + ' --> ' + strAmount));
    objCurListNode.appendChild(objNewListItemNode);
  }

  // move on to the next screen
  var strNextView = 'BankHistory';
  var objBrowser = document.getElementById('browser').object;
  objBrowser.goForward(document.getElementById(strNextView), strNextView);
  return;
}

function cbFailureMainBankHistoryInit(error) {
  alert(error);
  return;
}

// ------------------------

function onClickMainBankAddPayee(objEvent) {
  var strNewCustomer = document.getElementById('bankSetupNewCustomer').value;
  var objBankService = gobjTheServices.getBankService();
  objBankService.addCustomer(cbSuccessMainBankAddPayee, cbFailureMainBankAddPayee, strNewCustomer);
  return;
}

function cbSuccessMainBankAddPayee(response) {
  alert('Done!');
  return;    
}

function cbFailureMainBankAddPayee(error) {
  alert(error);  
  return;
}

// ------------------------

function onClickMainBankPay(event) {
  var strFrom = gstrUsername;
  var strTo = document.getElementById('mainBankPayPayee_To').value;
  var strAmount = document.getElementById('mainBankPayPayee_Amount').value;
  var objBankService = gobjTheServices.getBankService();
  objBankService.makePayment(cbSuccessMainBankMakePayment, cbFailureMainBankMakePayment, strFrom, strTo, strAmount);
  return;
}

function cbSuccessMainBankMakePayment(response) {
  alert('Done!');
  return;
}

function cbFailureMainBankMakePayment(error) {
  alert(error);
  return;
}

// == access (RESTful) CustomerService 

var gstrCustomerServiceUrl = gstrBaseUrl + '/CustomerService';
var gobjRestService = null;
function onClickMainCustomerGetAll(objEvent) {  
  gobjRestService = new XMLHttpRequest();
  gobjRestService.onreadystatechange = cbMainCustomerGetAll;
  gobjRestService.open('GET', gstrCustomerServiceUrl, true);
  gobjRestService.send(null);
  return;
}

function cbMainCustomerGetAll() {
  if (gobjRestService.readyState == 4) {
    if (gobjRestService.status == 200) {
      var objResult = document.getElementById('mainCustomer_Result');
      objResult.value = gobjRestService.responseText;
    } else {
      alert('Uppps ... not good :(');
    }
  }
  return;  
}

function onClickMainCustomerGetDetail(objEvent) {
  var strCustomerId = document.getElementById('mainCustomer_Id').value; 
  gobjRestService = new XMLHttpRequest();
  gobjRestService.onreadystatechange = cbMainCustomerGetDetail;
  gobjRestService.open('GET', gstrCustomerServiceUrl + '/Customer/' + strCustomerId, true);
  gobjRestService.send(null);
  return;  
}

function cbMainCustomerGetDetail() {
  if (gobjRestService.readyState == 4) {
    if (gobjRestService.status == 200) {
      var objXmlDoc = gobjRestService.responseXML;
      var strId = objXmlDoc.getElementsByTagName('id').item(0).firstChild.nodeValue;
      var strName = objXmlDoc.getElementsByTagName('name').item(0).firstChild.nodeValue;

      var objField = document.getElementById('mainCustomerDetail_Id');
      objField.value = strId;

      var objName = document.getElementById('mainCustomerDetail_Name');
      objName.value = strName;

      // ready to go ... show the customer details
      var strNextView = 'CustomerDetails';
      var objBrowser = document.getElementById('browser').object;
      objBrowser.goForward(document.getElementById(strNextView), strNextView);
    } else {
      alert('Uppps ... not good :(');
    }
  }
  return;  
}
