/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var dashcodePartSpecs = {
    "backButton": { "creationFunction": "CreatePushButton", "initialHeight": 30, "initialWidth": 70, "leftImageWidth": 16, "onclick": "myBackHandler", "rightImageWidth": 5, "text": "Back" },
    "browser": { "creationFunction": "CreateBrowser" },
    "button": { "creationFunction": "CreatePushButton", "initialHeight": 40, "initialWidth": 260, "leftImageWidth": 20, "onclick": "onClickMainSimpleSayHi", "rightImageWidth": 20, "text": "SayHi" },
    "button1": { "creationFunction": "CreatePushButton", "initialHeight": 40, "initialWidth": 260, "leftImageWidth": 20, "onclick": "onClickMainSimpleGreetMe", "rightImageWidth": 20, "text": "GreetMe" },
    "button2": { "creationFunction": "CreatePushButton", "initialHeight": 40, "initialWidth": 260, "leftImageWidth": 20, "onclick": "onClickMainBeverage", "rightImageWidth": 20, "text": "GetBeverage" },
    "button3": { "creationFunction": "CreatePushButton", "initialHeight": 40, "initialWidth": 260, "leftImageWidth": 20, "onclick": "onClickMainBankAddPayee", "rightImageWidth": 20, "text": "Add" },
    "button4": { "creationFunction": "CreatePushButton", "initialHeight": 40, "initialWidth": 260, "leftImageWidth": 20, "onclick": "onClickMainBankPay", "rightImageWidth": 20, "text": "Pay" },
    "button5": { "creationFunction": "CreatePushButton", "initialHeight": 40, "initialWidth": 181, "leftImageWidth": 20, "onclick": "onClickMainCustomerGetAll", "rightImageWidth": 20, "text": "GetAllCustomers" },
    "button6": { "creationFunction": "CreatePushButton", "initialHeight": 40, "initialWidth": 159, "leftImageWidth": 20, "onclick": "onClickMainCustomerGetDetail", "rightImageWidth": 20, "text": "GetCustomer" },
    "footer": { "creationFunction": "CreateText", "text": "Developed with Dashcode Using FUSE 2.1" },
    "header": { "creationFunction": "CreateHeader", "rootTitle": "CXF Demos" },
    "history": { "creationFunction": "CreatePushButton", "initialHeight": 55, "initialWidth": 240, "leftImageWidth": 28, "onclick": "onClickMainBankHistory", "rightImageWidth": 28, "text": "History" },
    "Item": { "creationFunction": "CreateText", "text": "Item" },
    "label": { "creationFunction": "CreateText", "text": "Item" },
    "label1": { "creationFunction": "CreateText", "text": "Item" },
    "list": { "creationFunction": "CreateList", "dataArray": ["Simple", "Beverage", "Bank", "Customer"], "labelElementId": "Item", "listStyle": "List.ROUNDED_RECTANGLE", "sampleRows": 3 },
    "list1": { "creationFunction": "CreateList", "dataArray": ["SayHi", "GreetMe"], "labelElementId": "label", "listStyle": "List.ROUNDED_RECTANGLE", "sampleRows": 3 },
    "login": { "creationFunction": "CreatePushButton", "initialHeight": 55, "initialWidth": 132, "leftImageWidth": 28, "onclick": "onClickMainBankLogin", "rightImageWidth": 28, "text": "Login" },
    "mainBankHistory_Transactions": { "creationFunction": "CreateList", "dataArray": [["dummy", "dummy"]], "labelElementId": "label1", "listStyle": "List.EDGE_TO_EDGE", "sampleRows": 3 },
    "payPayee": { "creationFunction": "CreatePushButton", "initialHeight": 55, "initialWidth": 240, "leftImageWidth": 28, "onclick": "onClickMainBankPayPayee", "rightImageWidth": 28, "text": "Pay Payee" },
    "setupPayee": { "creationFunction": "CreatePushButton", "initialHeight": 55, "initialWidth": 240, "leftImageWidth": 28, "onclick": "onClickMainBankSetupPayee", "rightImageWidth": 28, "text": "Setup Payee" },
    "stackLayout": { "creationFunction": "CreateStackLayout", "subviewsTransitions": [{ "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }] }
};
